repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4 # frozen: v3.21.2
    hooks:
      - id: pyupgrade

  # Autoformat: Python lint fixes
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
      - id: autoflake
        args:
          - --in-place

  # Autoformat: python imports
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort

  # Autoformat: Python code
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black

  # Lint: Python code
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  # Autoformat: markdown, yaml, javascript (see the file .prettierignore)
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier

  # autoformat HTML templates
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-jinja
        files: ".*templates/.*.html"
        types_or: ["html"]
        exclude: redoc.html
      - id: djlint-jinja
        files: ".*templates/.*.html"
        types_or: ["html"]

  # github actions security checks
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.24.1
    hooks:
      - id: zizmor
        args:
          - --fix

  # Autoformat and linting, misc. details
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
