name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run prek (pre-commit)
        uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2.0.3

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Start test container
        run: ./continuous_integration/before_install.sh

      - name: Install dependencies
        run: docker exec -i kerberosauthenticator-testing ./working/continuous_integration/install.sh

      - name: Run tests
        run: docker exec -i kerberosauthenticator-testing ./working/continuous_integration/script.sh
